language: php

# We want to test against PHP 5.3/5.4/5.5
php:
  - 5.5
  - 5.3
  - 5.4

# Separate different test suites
env:
  matrix:
    - TEST_SUITE=PHPTests
    - TEST_SUITE=JavascriptTests

matrix:
  exclude:
  - php: 5.4
    env: TEST_SUITE=JavascriptTests
  - php: 5.5
    env: TEST_SUITE=JavascriptTests

before_script:
  - uname -a
  - date
  - phantomjs --version
  - cd tests/

script: ./travis.sh